//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.30 at 12:58:08 AM GST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://soap.jee.mcnz.com/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.soap_test.models;
